Repository mamba-org/quetz, pull requests merged in 2022-05, with the labels that each got.

#525 fix mamba 0.23.0 compat
  plugins/quetz_mamba_solve/quetz_mamba_solve/solver.py
Labels: bug

#524 allow upload usage without conda-verify installed
  quetz_client/quetz_client/command_line.py
Labels: enhancement

#523 log errors of background tasks
  quetz/main.py
  quetz/utils.py
Labels: enhancement

#526 Fix PAM authentication log message
  quetz/authentication/pam.py
Labels: bug

#530 fix compatibility with latest starlette
  quetz/authentication/pam.py
Labels: bug

#529 fix proxy channels noarch and gzip repodata
  quetz/main.py
  quetz/tasks/mirror.py
Labels: bug

#531 Automated Changelog Entry for 0.4.3 on main
  CHANGELOG.md
Labels: documentation

#532 Log post_index_creation exceptions
  quetz/tasks/indexing.py
Labels: enhancement

#534 improve logging
  quetz/cli.py
  quetz/tasks/mirror.py
Labels: enhancement

#537 Automated Changelog Entry for 0.4.4 on main
  CHANGELOG.md
Labels: documentation
