Repository mamba-org/quetz, pull requests merged in 2022-07, with the labels that each got.

#548 Adds a new endpoint to check if the user already signed the TOS
  environment.yml
  plugins/quetz_tos/quetz_tos/api.py
  quetz/tests/test_cli.py
Labels: enhancement

#541 channels with dots in their name cause a crash in indexing
  quetz/tasks/indexing.py
Labels: bug

#533 Add upload endpoint
  quetz/main.py
  quetz/pkgstores.py
Labels: enhancement

#551 Remove package from repodata.json
  quetz/main.py
  quetz/tasks/indexing.py
  quetz/tests/api/test_main_packages.py
Labels: bug

#554 Remove an uploaded package whose filename does not match the package name
  quetz/main.py
  quetz/tests/api/test_main_packages.py
Labels: bug

#555 Fixes issues and tests on indexes
  quetz/main.py
  quetz/tests/api/__init__.py
  quetz/tests/api/conftest.py
  quetz/tests/api/test_main_packages.py
  quetz/tests/conftest.py
  quetz/tests/data/test-package-0.1-0_copy.tar.bz2
  quetz/tests/test_dao.py
  quetz/tests/test_indexing.py
  quetz/tests/test_jobs.py
  quetz/tests/test_tasks.py
  quetz/tests/test_versionorder.py
Labels: bug, maintenance
