Repository mamba-org/quetz, pull requests merged in 2022-03, with the labels that each got.

#496 make mamba solver work with latest mamba release
  plugins/quetz_mamba_solve/quetz_mamba_solve/solver.py
  pyproject.toml
Labels: bug

#490 Make cache timeout for GCS configurable
  docs/source/deploying/configuration.rst
  environment.yml
  quetz/config.py
  quetz/pkgstores.py
  setup.cfg
Labels: enhancement

#497 attempt to fix CI
  .github/workflows/ci.yml
Labels: enhancement

#501 update all js
  quetz_frontend/package-lock.json
  quetz_frontend/package.json
  quetz_frontend/src/App.vue
  quetz_frontend/src/components/HeaderComponent.vue
  quetz_frontend/src/main.js
  quetz_frontend/src/router.js
  quetz_frontend/src/views/ApiKeysView.vue
  quetz_frontend/src/views/ChannelsView.vue
  quetz_frontend/src/views/JobsView.vue
  quetz_frontend/src/views/PackageView.vue
  quetz_frontend/src/views/PackagesView.vue
  quetz_frontend/src/views/TasksView.vue
  quetz_frontend/src/views/UsersView.vue
Labels: enhancement, maintenance

#502 fix some pytest and sqlalchemy warnings
  plugins/quetz_harvester/tests/conftest.py
  quetz/authentication/registry.py
  quetz/dao.py
  quetz/db_models.py
  quetz/jobs/models.py
  quetz/jobs/runner.py
  quetz/tasks/workers.py
  quetz/testing/mockups.py
  quetz/tests/api/conftest.py
  quetz/tests/api/test_channels.py
  quetz/tests/conftest.py
  quetz/tests/test_jobs.py
  quetz/tests/test_mirror.py
  quetz/utils.py
Labels: maintenance

#503 Automated Changelog Entry for 0.4.0 on master
  CHANGELOG.md
Labels: documentation

#500 Unpin h2
  environment.yml
  setup.cfg
Labels: maintenance
