Repository mamba-org/quetz, pull requests merged in 2022-04, with the labels that each got.

#513 Fix CI
  .pre-commit-config.yaml
  environment.yml
  quetz/authentication/pam.py
Labels: dependencies, maintenance

#512 Make GCS bucket location configurable
  docs/source/deploying/configuration.rst
  environment.yml
  quetz/config.py
  quetz/pkgstores.py
Labels: enhancement

#514 Automated Changelog Entry for 0.4.1 on main
  CHANGELOG.md
Labels: documentation

#517 Fix gcs region config entry
  quetz/config.py
Labels: bug

#519 Automated Changelog Entry for 0.4.2 on main
  CHANGELOG.md
Labels: documentation

#507 Move httpx as dependency
  setup.cfg
Labels: dependencies, maintenance

#521 Use infodata['size'] for s3fs
  quetz/pkgstores.py
Labels: bug
