Repository mamba-org/quetz, pull requests merged in 2023-08, with the labels that each got.

#657 Fix postgres pool size
  quetz/deps.py
Labels: enhancement

#638 Consider packages.conda for index update and channel mirroring
  plugins/quetz_content_trust/quetz_content_trust/main.py
  quetz/tasks/indexing.py
  quetz/tasks/mirror.py
  quetz/tests/data/other-package-0.2-0.conda
  quetz/tests/test_mirror.py
Labels: enhancement

#635 Make upload routes consistent with each other
  quetz/main.py
  quetz/tests/api/test_main_packages.py
Labels: maintenance

#656 Migrate to Pydantic v2
  environment.yml
  quetz/db_models.py
  quetz/jobs/api.py
  quetz/jobs/rest_models.py
  quetz/main.py
  quetz/metrics/rest_models.py
  quetz/rest_models.py
  quetz/tests/api/test_api_keys.py
  quetz/tests/api/test_channels.py
  quetz/tests/api/test_main_packages.py
  quetz/tests/test_jobs.py
  quetz/tests/test_mirror.py
  setup.cfg
Labels: enhancement, dependencies

#655 Add migration script for scoped API keys
  quetz/migrations/versions/3ba25f23fb7d_update_scoped_api_key_uploader_id.py
Labels: bug
