Repository mamba-org/quetz, pull requests merged in 2023-06, with the labels that each got.

#633 enhancement: sanitize DB urls before printing
  quetz/cli.py
  quetz/database.py
  quetz/tests/test_database.py
Labels: enhancement

#631 add: osx-arm64 version for testing on newer apple devices
  README.md
  download-test-package.sh
Labels: maintenance

#636 Add GCS env vars
  .github/workflows/ci.yml
Labels: maintenance

#637 Run CI on main branch
  .github/workflows/ci.yml
Labels: maintenance

#626 Add async friendly upload
  .pre-commit-config.yaml
  environment.yml
  quetz/main.py
  quetz/pkgstores.py
  quetz/tests/test_pkg_stores.py
  setup.cfg
Labels: enhancement

#651 Checkout source code from fork
  .github/workflows/ci.yml
Labels: maintenance

#650 Fix event loop errors
  environment.yml
  quetz/pkgstores.py
Labels: bug

#643 Bump pyright-python version
  .pre-commit-config.yaml
  quetz/authentication/oauth2.py
  quetz/tests/authentification/test_oauth.py
Labels: maintenance

#644 Use PEP-593 Annotated for options and arguments in CLI commands
  quetz/cli.py
Labels: maintenance

#641 Do not pass pooling arguments to sqlite
  docs/source/deploying/configuration.rst
  quetz/config.py
  quetz/database.py
Labels: bug
