Repository mamba-org/quetz, pull requests merged in 2023-02, with the labels that each got.

#594 Fix upload endpoint
  quetz/cli.py
  quetz/config.py
  quetz/main.py
  quetz/pkgstores.py
Labels: bug

#597 Fix upload endpoint
  quetz/main.py
Labels: bug

#565 remove frontend
  Dockerfile
  quetz_frontend/.gitignore
  quetz_frontend/README.md
  quetz_frontend/babel.config.js
  quetz_frontend/package-lock.json
  quetz_frontend/package.json
  quetz_frontend/public/avatar.jpg
  quetz_frontend/public/favicon.ico
  quetz_frontend/public/index.html
  quetz_frontend/src/App.vue
  quetz_frontend/src/assets/logo.png
  quetz_frontend/src/components/HeaderComponent.vue
  quetz_frontend/src/main.js
  quetz_frontend/src/router.js
  quetz_frontend/src/styles/_carbon.scss
  quetz_frontend/src/views/ApiKeysView.vue
  quetz_frontend/src/views/ChannelsView.vue
  quetz_frontend/src/views/JobsView.vue
  quetz_frontend/src/views/PackageView.vue
  quetz_frontend/src/views/PackagesView.vue
  quetz_frontend/src/views/TasksView.vue
  quetz_frontend/src/views/UsersView.vue
  quetz_frontend/vue.config.js
Labels: enhancement

#598 Make `quetz` compatible with SQLAlchemy 2.0
  plugins/quetz_conda_suggest/quetz_conda_suggest/main.py
  plugins/quetz_content_trust/quetz_content_trust/db_models.py
  plugins/quetz_runexports/quetz_runexports/main.py
  quetz/dao.py
  quetz/db_models.py
  quetz/migrations/env.py
  quetz/tests/test_cli.py
  quetz/tests/test_jobs.py
  quetz/tests/test_mirror.py
Labels: bug

#601 Update check-release action to v2
  .github/workflows/ci.yml
  environment.yml
  pyproject.toml
Labels: maintenance

#602 Remove xattr as hard dependency
  .github/workflows/ci.yml
  quetz/pkgstores.py
  setup.cfg
Labels: dependencies, maintenance

#604 Fix ReadTheDocs
  .readthedocs.yml
Labels: maintenance

#605 Try to fix ReadTheDocs 2
  .readthedocs.yml
Labels: maintenance

#608 Add prettier pre-commit hook
  .github/workflows/ci.yml
  .github/workflows/docker-build-push.yml
  .github/workflows/lint.yml
  .github/workflows/sphinx.yml
  .gitignore
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  RELEASE.md
  docker-compose.yml
  docker/prometheus.yml
  environment.yml
  plugins/quetz_content_trust/tests/data/key_mgr.json
  plugins/quetz_content_trust/tests/data/root.json
  plugins/quetz_repodata_patching/README.md
  plugins/quetz_runexports/README.md
  plugins/quetz_sql_authenticator/README.md
  plugins/quetz_transmutation/README.md
  quetz/basic_frontend/index.html
Labels: maintenance

#607 Add pyright pre-commit hook
  .github/workflows/lint.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  environment.yml
  pyproject.toml
Labels: maintenance

#610 Enable pyright reportPrivateImportUsage
  pyproject.toml
  quetz/main.py
  quetz/pkgstores.py
  quetz/tasks/mirror.py
Labels: maintenance

#611 Enable pyright reportOptionalSubscript
  pyproject.toml
  quetz/authentication/base.py
  quetz/migrations/env.py
Labels: maintenance

#612 Enable pyright reportOptionalOperand
  pyproject.toml
  quetz/tasks/workers.py
Labels: maintenance

#613 Enable pyright reportOptionalMemberAccess
  plugins/quetz_conda_suggest/tests/test_quetz_conda_suggest.py
  plugins/quetz_runexports/quetz_runexports/api.py
  plugins/quetz_tos/quetz_tos/api.py
  pyproject.toml
  quetz/metrics/tasks.py
Labels: maintenance

#614 Enable pyright reportMissingModuleSource
  pyproject.toml
  quetz/tasks/workers.py
Labels: maintenance

#589 Remove old `quetz-client`
  README.md
  quetz_client/.flake8
  quetz_client/pyproject.toml
  quetz_client/quetz_client/__init__.py
  quetz_client/quetz_client/_version.py
  quetz_client/quetz_client/command_line.py
  quetz_client/setup.cfg
  quetz_client/setup.py
Labels: maintenance

#593 Move SQL authenticator plugin to own repo
  README.md
  plugins/quetz_sql_authenticator/README.md
  plugins/quetz_sql_authenticator/quetz_sql_authenticator/__init__.py
  plugins/quetz_sql_authenticator/quetz_sql_authenticator/api.py
  plugins/quetz_sql_authenticator/quetz_sql_authenticator/db_models.py
  plugins/quetz_sql_authenticator/quetz_sql_authenticator/main.py
  plugins/quetz_sql_authenticator/quetz_sql_authenticator/migrations/__init__.py
  plugins/quetz_sql_authenticator/quetz_sql_authenticator/migrations/versions/__init__.py
  plugins/quetz_sql_authenticator/quetz_sql_authenticator/migrations/versions/db1fe7199ca1_.py
  plugins/quetz_sql_authenticator/setup.py
  plugins/quetz_sql_authenticator/tests/conftest.py
  plugins/quetz_sql_authenticator/tests/test_quetz_sql_authenticator.py
Labels: maintenance

#615 Enable pyright reportMissingImports
  environment.yml
  pyproject.toml
Labels: maintenance

#609 Fix unbound variables
  plugins/quetz_content_trust/quetz_content_trust/main.py
  plugins/quetz_repodata_zchunk/tests/test_main.py
  pyproject.toml
  quetz/authentication/auth_dao.py
  quetz/cli.py
  quetz/config.py
  quetz/dao.py
  quetz/jobs/runner.py
  quetz/pkgstores.py
  quetz/tasks/indexing.py
  quetz/tasks/mirror.py
  quetz/testing/fixtures.py
  quetz/tests/test_pkg_stores.py
  quetz/utils.py
Labels: bug
